### ISSUE TITLE
Include request body in signature check

### ISSUE THREAD

**Issue by timotree3** [Holo-Host/hp-admin-crypto#25]
We don't actually include the request body in our signature check. On [this line](https://github.com/Holo-Host/hp-admin-crypto/blob/95b2f661e4573ba7879afb38618d9fdd0c290727/server/src/main.rs#L105), we include `body` in the signed payload, but body is always an empty string here, because the request we are looking at is always a GET to `/auth/` coming from nginx, which doesn't have a body. We would need to encode `X-Original-Body` or something in a header in order to include it in the signature check.

What this means from a practical perspective is that an attacker who has observed a plaintext request of Alice doing an operation on her HoloPort (e.g. `register-happ` or editing her holoport name), can perform the same type of action on Alice's holoport but with different parameters (e.g. registering a different happ)

This is not a super big deal since all of the currently possible operations are relatively harmless.

**Comment by peeech** [comment]
With merging #26 this issue has been automatically resolved
