### ISSUE TITLE
User is not able to log into holoport with correct credentials

### ISSUE THREAD

**Issue by peeech** [Holo-Host/hp-admin-crypto#29]
User gets 401 when trying to access Host Console. User's credentials are [here](https://github.com/Holo-Host/hp-admin-crypto/blob/signing-bug/server/src/tests.rs#L13)

You can see that [verify_hp_admin_match](https://github.com/Holo-Host/hp-admin-crypto/blob/signing-bug/server/src/tests.rs#L21) test will pass, but [check_signature_matches_client](https://github.com/Holo-Host/hp-admin-crypto/blob/signing-bug/server/src/tests.rs#L38) does not.

**Comment by peeech** [comment]
This points to the fact that supplied credentials (login, pass, holoport_id) create same keypair as during quickstart process, but those credentials are not creating right signature.

**Comment by peeech** [comment]
I ran a [www test](https://github.com/Holo-Host/hp-admin-crypto/tree/signing-bug/client/tests/www) with those credentials and I can see that they produce a signature `PUDkdJgWkEtOT5o8PsxXPPFFEKikys34XyZbLcEgD2n7BKBQ14UqT6uwJkWJRCHnZTkeJgCIJU6UBjwHKYjvCg` which is different from the one produced by host console ui. Funny enough this new signature passes [check_signature_matches_client](https://github.com/Holo-Host/hp-admin-crypto/blob/signing-bug/server/src/tests.rs#L38) test!!!

**Comment by peeech** [comment]
This means that Host Console UI is creating wrong signature.

Now when I lower case email address I am able to get a signature `XtYletKLUs0nyWT51AL32LhElJBKZ65QYCDvM9jU11mHdUgqa27kNox6HamMKtj3a6NJUjPJmLSTfJjMQeUSAA` which matches one produced by Host Console UI, but it does not pass [check_signature_matches_client](https://github.com/Holo-Host/hp-admin-crypto/blob/signing-bug/server/src/tests.rs#L38) test

**Comment by peeech** [comment]
So an issue is:
Host console lower-cases email address before using it for creating signing keypair. But Quickstart does not. So Quickstart will create a different signing keypair than Host Console every time email contains Upper Case letters.

**Comment by peeech** [comment]
The solution here is to lower case email address all across the board, which Host console [already does](https://github.com/Holo-Host/host-console-ui/blob/develop/src/pages/LoginPage.vue#L83).

**Comment by peeech** [comment]
I checked a config file on user's holoport (`hp-primary-13lth.json`). I discovered that `V2.settings.admin.email` is lower cased while user's oryginal email starts with Capital letter. So I generated `V2.settings.admin.public_key` using [verify_hp_admin_match](https://github.com/Holo-Host/hp-admin-crypto/blob/signing-bug/server/src/tests.rs#L21) test for two cases:
1. for an email starting with Capital letter it reads `Q+mHyDrZO/I7MBRNexRVFp2Bm1ASPcJA8MgBB645VnU`
2. for an email all lowercased it reads `plQxMD68IX/XOslW5c2e6K0cyqhwqpnvqIkoCuNgkio`

Value of `V2.settings.admin.public_key` from point 1 was originally  in `hp-primary-13lth.json`. With this value user is not able to log in.

After replacing `V2.settings.admin.public_key`  with value from point 2 I could log in to holoport.

This means that if during quickstart user enters their email address with at least one Capital letter their `V2.settings.admin.public_key` will be derived using this original capitalization of an email. In the meantime email address is lowercased all across holo infrastructure, so user will never be able to log into their holoport.

**Comment by peeech** [comment]
So now I have to figure it out how is it possible that `V2.settings.admin.public_key` is derived from a non-lowercased email address!

**Comment by peeech** [comment]
To reproduce:
Go to quickstart.holo.host and create config file. When asked for an email enter email address with capitalized letters.
When you inspect config file you will find out that email in config also contains capitalized letters, while it should be lower-cased.

**Comment by peeech** [comment]
Quickstart generates config file in [this line of code](https://github.com/Holo-Host/hpos-config/blob/master/gen-web/src/index.js#L592) from `user` object populated here:
https://github.com/Holo-Host/hpos-config/blob/f95d8da67dc87cef382209f35e31e34a7e51ad18/gen-web/src/index.js#L550-L552
So obviously `email` field is lower-cased. How on earth is a capitalized email making it to config file????

**Comment by alastairong** [comment]
@peeech I manually edited the user's email on the V2 config. It was originally upper case in the file. I forgot to mention that.

**Comment by alastairong** [comment]
Although I don't think that solves the mystery since as your code link points out, quickstart itself should be lower-casing the email for generating keys

**Comment by peeech** [comment]
It totally does. Quickstart passes email to config creating function without lower-casing. As a consequence `admin.pubkey` is derived from wrong data and signature check fails!

**Comment by peeech** [comment]
Further investigation shows that it is a deployment issue or caching issue. 

I compiled and ran locally [quickstart](https://github.com/Holo-Host/hpos-config/tree/master/gen-web) page on master. It works as expected - it will lowercase an email and create correct `admin.pub_key`.

You can see it in a following way:
- go to https://quickstart.holo.host/
- in step 1 enter email that contains upper case
- in step 4 you will see that an email is displayed with upper case letters
a correct behavior is that step 4 should already display lower-cased email address. That's what happens on `master` when run locally.

**Comment by peeech** [comment]
So I am going to re-deploy master to quickstart and see what happens.

**Comment by peeech** [comment]
It turns out that routes on cloudflare were messed up and quickstart.holo.host was pointing to an old version of code. Fixed on cloudflare
